version: '3'
services:

  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

